### ISSUE TITLE
websocket messages 

### ISSUE THREAD

**Issue by jiajunxiong** [okcoin-okex/API-docs-OKEx.com#72]
Websocket onmessage:
ws.onmessage = (event: any) => {
    const message: any = JSON.parse(event.data)
    if ("channel" in message[0]) {
        if (message[0].channel === 'ok_sub_futureusd_trades') {
            const orders = message[0].data
            handleOrder(orders)
        }
    }
}
TypeError: Cannot read property 'channel' of undefined
    at WebSocket.exchWs.onmessage (C:\projects\oms-root\exchgw\okex\okex.js:132:24)
    at WebSocket.onMessage (C:\projects\oms-root\exchgw\okex\node_modules\ws\lib\event-target.js:120:16)
    at emitOne (events.js:116:13)
    at WebSocket.emit (events.js:211:7)
    at Receiver.receiverOnMessage (C:\projects\oms-root\exchgw\okex\node_modules\ws\lib\websocket.js:718:20)
    at emitOne (events.js:116:13)
    at Receiver.emit (events.js:211:7)
    at Receiver.dataMessage (C:\projects\oms-root\exchgw\okex\node_modules\ws\lib\receiver.js:414:14)
    at perMessageDeflate.decompress (C:\projects\oms-root\exchgw\okex\node_modules\ws\lib\receiver.js:371:23)
    at _decompress (C:\projects\oms-root\exchgw\okex\node_modules\ws\lib\permessage-deflate.js:307:9)
    at _inflate.flush (C:\projects\oms-root\exchgw\okex\node_modules\ws\lib\permessage-deflate.js:389:7)
    at afterWrite (_stream_writable.js:454:3)
    at onwrite (_stream_writable.js:445:7)
    at InflateRaw.afterTransform (_stream_transform.js:90:3)
    at Zlib.callback (zlib.js:515:5)

**Comment by martin-g** [comment]
If `message` is not array, then `message[0]` will be `undefined` and you will get this error.

**Comment by jiajunxiong** [comment]
Then how could I just select "ok_sub_futureusd_trades" channel messages?

**Comment by martin-g** [comment]
Add some logging and see what happens.
You should not assume that all messages have the same structure.
